materials_path = "config/blurred/materials.toml"

[[entities]]
# ground
type = "Plane"
material = "green"
point = [0, -1.5, 0]
normal = [0, 1, 0]

[[entities]]
# center
type = "Sphere"
material = "blue"
center = [4.0, 0.0, 0.0]
radius = 1.5
delta_point = [0, 0.6, 0]

[[entities]]
# left top
type = "Sphere"
material = "fuzz_purple"
center = [4.0, 1.5, -1.5]
radius = 0.6

[[entities]]
# right
type = "Sphere"
material = "transp"
center = [3.0, 0.0, 3.5]
radius = 1.5

[[entities]]
# right inner
type = "Sphere"
material = "transp_inner"
center = [3.0, 0.0, 3.5]
radius = 1.2

[[entities]]
# left
type = "Sphere"
material = "mirror_yellow"
center = [4.0, 0.0, -3.0]
radius = 1.5
delta_point = [-0.6, 0.6, 0]
