[[materials]]
name = "light"
type = "DiffuseLight"
# color = [3, 3, 3]
color = [6, 6, 6]

[[materials]]
name = "blue"
type = "PolarChecker"
color1 = [0.1, 0.2, 0.5]
color2 = [0.8, 0.8, 0.8]
ntheta = 18
nphi = 36

[[materials]]
name = "pink"
type = "Lambertian"
albedo = [0.84, 0.55, 0.67]

[[materials]]
name = "smoky"
type = "Smoke"
k = 4

[[materials]]
name = "palepink"
type = "Lambertian"
albedo = [0.92, 0.67, 0.88]

[[materials]]
name = "green"
type = "Lambertian"
albedo = [0.1, 0.5, 0.2]

[[materials]]
name = "mirror_yellow"
type = "FuzzedMetal"
albedo = [0.8, 0.6, 0.2]
fuzz = 0.02

[[materials]]
name = "fuzz_purple"
type = "FuzzedMetal"
albedo = [0.58, 0.23, 0.72]
# fuzz is between 0 and 1
fuzz = 0.1

[[materials]]
name = "transp"
type = "Dielectric"
eta = 1.33
