# materials_path = "config/lens/materials.toml"
materials_path = "config/dark/materials.toml"

[background]
type = "Pure"
color = [0.2, 0.24, 0.4]

# [[entities]]
# type = "Box"
# material = "palepink"
# a = [2.0, -1.5, 0.5]
# b = [2.2, -1.5, 1.0]
# c = [2.5, -1.5, 0.3]
# d = [2.0, -0.5, 0.5]

[[entities]]
type = "SmokeBox"
material = "smoky"
a = [2.0, -1.4, 0.5]
b = [2.2, -1.4, 1.0]
c = [2.5, -1.4, 0.3]
d = [2.0, 0.0, 0.5]

[[entities]]
# light
type = "Parallelogram"
material = "light"
a = { world = [3, 2, -1.5] }
b = { world = [4, 2, -1.5] }
c = { world = [3, 2, 1.5] }

[[entities]]
# ground
type = "Plane"
material = "green"
point = [0, -1.5, 0]
normal = [0, 1, 0]

[[entities]]
# back
type = "Triangle"
material = "pink"
a = { world = [8, 0.0, 2.0], uv = [1, 0] }
b = { world = [8, 0.0, -2.0], uv = [0, 1] }
c = { world = [8, 3.0, 0.0], uv = [0, 0] }

[[entities]]
# center
type = "Sphere"
material = "blue"
center = [4.0, 0.0, 0.0]
radius = 1.5

[[entities]]
# purple
type = "Sphere"
material = "fuzz_purple"
center = [2.0, -0.9, -1.0]
radius = 0.4

[[entities]]
# right
type = "Sphere"
material = "transp"
center = [3.0, -0.7, 2]
radius = 0.8

[[entities]]
# left
type = "Sphere"
material = "mirror_yellow"
center = [4.0, 0.0, -3.0]
radius = 1.5
