[[materials]]
name = "light"
type = "DiffuseLight"
color = [5, 5, 5]

[[materials]]
name = "pink"
type = "FuzzedMetal"
albedo = [0.84, 0.55, 0.67]
# fuzz is between 0 and 1
fuzz = 0.15

[[materials]]
name = "white"
type = "Lambertian"
albedo = [0.9, 0.9, 0.9]

[[materials]]
name = "black"
type = "Lambertian"
albedo = [0.3, 0.3, 0.3]

[[materials]]
name = "palepink"
type = "Lambertian"
albedo = [0.92, 0.67, 0.88]

[[materials]]
name = "smoky"
type = "Smoke"
k = 4

[[materials]]
name = "grass"
type = "Lambertian"
albedo = [0.49, 0.922, 0.522]

[[materials]]
name = "sky"
type = "FuzzedMetal"
albedo = [0.682, 0.875, 0.992]
# fuzz is between 0 and 1
fuzz = 0.18

[[materials]]
name = "green"
type = "Lambertian"
albedo = [0.1, 0.5, 0.2]

[[materials]]
name = "mirror_yellow"
type = "FuzzedMetal"
albedo = [0.8, 0.6, 0.2]
fuzz = 0.05

[[materials]]
name = "fuzz_purple"
type = "FuzzedMetal"
albedo = [0.58, 0.23, 0.72]
# fuzz is between 0 and 1
fuzz = 0.1

[[materials]]
name = "glass"
type = "Dielectric"
eta = 1.33


[[materials]]
name = "bluegrid"
type = "PolarChecker"
color1 = [0.1, 0.2, 0.5]
color2 = [0.8, 0.8, 0.8]
ntheta = 18
nphi = 36

[[materials]]
name = "mirror"
type = "Metal"
albedo = [0.996, 0.984, 0.392]
